[build-system]
requires = ["setuptools", "wheel", "grpcio-tools", "mypy-protobuf"]
build-backend = "setuptools.build_meta"

[project]
name = "blackwhale-proto"
version = "1.0.0"
dependencies = ["grpcio"]

[tool.setuptools.packages.find]
where = ["src"]